title: Bits y Tips de Linkfy
description: Artículos sobre programación, y todo lo que voy aprendiendo
baseurl: "/bitsytips"

markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
